"""
Image feature extraction using HD-Staining model Inference Utilities

This script applies the HD-Staining model to whole-slide images (WSIs) to:
    - segment nuclei,
    - extract nucleus-level features,

It is organized for reuse and publication on GitHub

Example
-------
python extract_image_feature.py \
    --input-dir /path/to/input_slides \
    --output-dir /path/to/output \
    --model-dir /path/to/hd_staining_model \
    --slide-id 5_CytAssist_11mm_FFPE_Human_Ovarian_Carcinoma_tissue_image
"""

import os
import sys
import re
import copy
import math
import time
import yaml
import torch
import scipy
import random
import warnings
import numpy as np
import pandas as pd
import cv2
from PIL import Image
import matplotlib
import matplotlib.pyplot as plt
import skimage
from skimage import io, morphology, feature
from skimage.draw import polygon, rectangle
import openslide
from openslide import open_slide, ImageSlide
import tifffile as tiff 
import xml.etree.ElementTree as ET
import torchvision.models.detection as tmdet
from torchvision.ops import boxes as box_ops
from torch.jit.annotations import Tuple, List, Dict, Optional

# Turn off warnings
if not sys.warnoptions:
    warnings.simplefilter('ignore')
Image.MAX_IMAGE_PIXELS = None

# Input self-defined functions

BREAST_MODEL_ROOT = "./models/image/"
MRCNN_PKG_ROOT = os.path.join(BREAST_MODEL_ROOT, "mrcnn_pkg")

sys.path.append(BREAST_MODEL_ROOT)
sys.path.append(MRCNN_PKG_ROOT)

from utils import (
    COLORS,
    CLASSES,
    CLASSES_,
    DEFAULT_DATASET_CONFIG,
    Dataset,
    normalizer,
    MODEL_CONFIG,
    DEFAULT_TRAIN_CONFIG,
    MaskRCNNModel_NuCLS,
)

import mrcnn as mrcnn
import utils_image_dannie as uimg_d


class model_parameters:
    """
    Parameters for the model to segment different types of nuclei on pathology slides
    """
    stain_mean = [168.05047310350506, 168.05047310350506, 162.54708725145446]
    stain_std = [51.83780744440758, 51.83780744440758, 43.12277861396769]
    
    classes  = ['tumor', 'stroma', 'lymphocyte', 'blood', 
                'macrophage', 'necrosis', 'ductal epithelium']

    rgb_markers = {'tumor': [0, 255, 0], 
                   'stroma': [255, 0, 0], 
                   'lymphocyte': [0, 0, 255], 
                   'blood': [255, 0, 255], 
                   'macrophage': [255, 255, 0], 
                   'necrosis': [0, 148, 225], 
                   'ductal epithelium': [100, 0, 255]}

# Update model config for validation
MODEL_CONFIG['transform']['min_size'] = 512
MODEL_CONFIG['transform']['max_size'] = 512
print(f'model config: {MODEL_CONFIG}')

# Set up dataset & dataloader for inference
dataset_config_infer = copy.deepcopy(DEFAULT_DATASET_CONFIG)
dataset_config_infer['output_size'] = (MODEL_CONFIG['transform']['min_size'], MODEL_CONFIG['transform']['min_size'])
dataset_config_infer
print(f'\ndataset config: {dataset_config_infer}')


def check_white(image):
    """
    Check whether there is enough signal in the input image

    Arg:
    :param image: (matrix) image object

    :return:
        Boolean (true indicating the image is almost completely white)
    """
    image_average = np.average(image)
    image_var = np.var(image)
    return (image_average >= 230) or (image_var <= 100)
    
    
def format_image(image, normalizer, model_device, mag_ratio=1):
    """
    Convert the image format from numpy.array to torch.Tensor

    Arg:
    :param image: (matrix) image object
    :param normalizer: (function) normalization function for the input image
    :param model_device: (object) device on which the torch.Tensor will be allocated
    :param mag_ratio: (float) ratio between model magnitude and image magnitude

    :return:
        image in the torch.Tensor format
    """
    if mag_ratio != 1:
        image = skimage.transform.rescale(image, mag_ratio, preserve_range=True, multichannel=True, 
                                          order=1).astype(np.uint8)
    normalized_image = normalizer(image)
    image_tensor = torch.tensor(np.transpose(normalized_image, (2, 0, 1)).astype(float))
    image_tensor = image_tensor.permute(1, 2, 0).cpu().numpy()
    image_tensor = torch.from_numpy(image_tensor).to(model_device).permute(2, 0, 1)
    image_tensor = torch.stack([image_tensor]).float().to(model_device)
    return image_tensor

def postprocess_prediction(pred, ratio_thresh=0.6):
    """
    There might be several different prediction results over the same region on the image. By this function,
    it only keeps the class with the highest possibility.

    Args:
    :param pred: (list) results generated by the HD-Staining model
    :param ratio_thresh: (0-1 float) threshold used to determine too much overlapping

    :return:
        a dictionary containing processed prediction results without overlapping
    """
    # Transfer model prediction results from torch.Tensor to numpy.array
    masks = pred[0]['masks']
    if masks.size()[0] == 1:
        masks = masks[0].permute(1, 2, 0).detach().cpu().numpy()
    else:
        masks = masks.squeeze().permute(1, 2, 0).detach().cpu().numpy()
    masks = ((masks>=0.5)*1).astype(np.int)
    class_ids = pred[0]['labels']
    class_ids = class_ids.detach().cpu().numpy()
    boxes = pred[0]['boxes']
    boxes = boxes.detach().cpu().numpy()
    scores = pred[0]['scores']
    scores = scores.detach().cpu().numpy()

    # (1) Filter based on area
    to_keep = []
    for i in range(masks.shape[2]):
        pos = np.where(masks[:, :, i])
        if len(pos[0]>0):
            if np.max(pos[1])>np.min(pos[1]) and np.max(pos[0])>np.min(pos[0]):
                to_keep.append(i)
    masks = masks[:, :, to_keep]
    class_ids = class_ids[to_keep]
    boxes = boxes[to_keep]
    scores = scores[to_keep]

    # (2) Filter based on overlaps
    masks_check = masks.copy()
    occlusion = np.ones(np.shape(masks_check)[0:2])
    to_keep = []
    for j in range(masks_check.shape[2]):
        # Remove the mask with tooooo much overlapping with previously detected region
        original_area = np.sum(masks_check[:, :, j])
        masks_check[:, :, j] = masks_check[:, :, j] * occlusion
        new_area = np.sum(masks_check[:, :, j])
        if new_area > 0 and new_area / original_area > ratio_thresh:
            to_keep.append(True)
            occlusion = np.logical_and(occlusion, np.logical_not(masks_check[:, :, j]))
        else:
            to_keep.append(False)
    masks = masks[:, :, to_keep]
    class_ids = class_ids[to_keep]
    boxes = boxes[to_keep]
    scores = scores[to_keep]
    
    # Collect processed model prediction results in a dictionary
    processed_pred = {'masks': masks, 
                      'class_ids': class_ids,
                      'boxes': boxes,
                      'scores': scores}
    return processed_pred

def get_box_features(model, features, proposals, patch_size=(512, 512)):
    """
    Extract box features from the HD-Staining model

    Args:
    :param model: the HD-Staining model for nuclei segmentation and classification
    :param features: (collections.OrderedDict) features from the backbone of the HD-Staining model
    :param proposals: (list) proposals from the rpn of the HD-Staining model
    :param patch_size: (tuple) a tuple containing two numbers (the first one indicating height and the second one
    indicating width of the patch)

    :return:
        - box_features
        - pred_boxes
        - pred_scores
    """
    # Get box_features for each proposal
    box_features = model.netG.roi_heads.box_roi_pool(features, proposals, [patch_size])
    box_features = model.netG.roi_heads.box_head(box_features)
    
    # Get pred_boxes and corresponding pred_scores for each proposal
    class_logits, box_regression = model.netG.roi_heads.box_predictor(box_features)
    pred_boxes = model.netG.roi_heads.box_coder.decode(box_regression, proposals)
    pred_boxes = box_ops.clip_boxes_to_image(pred_boxes, patch_size)
    pred_boxes = pred_boxes.reshape(-1, 4)
    pred_boxes = pred_boxes.detach().cpu().numpy()
    pred_scores = torch.nn.functional.softmax(class_logits, -1)
    pred_scores = pred_scores.reshape(-1)
    pred_scores = pred_scores.detach().cpu().numpy()
    return box_features, pred_boxes, pred_scores

def get_mask_features(model, processed_pred, features, patch_size=(512, 512)):
    """
    Extract mask features from the HD-Staining model

    Args:
    :param model: the HD-Staining model for nuclei segmentation and classification
    :param processed_pred: (dict) processed prediction results without overlapping
    :param features: (collections.OrderedDict) features from the backbone of the HD-Staining model
    :param patch_size: (tuple) a tuple containing two numbers (the first one indicating height and the second one
    indicating width of the patch)

    :return:
        mask_features for each detected nucleus
    """
    boxes = processed_pred['boxes']
    mask_proposals = [torch.tensor(boxes).to(model.netG.device)]
    mask_features = model.netG.roi_heads.mask_roi_pool(features, mask_proposals, [patch_size])
    mask_features = model.netG.roi_heads.mask_head(mask_features)
    return mask_features

def get_nucleus_features(processed_pred, model_classes, box_features, pred_boxes, pred_scores, mask_features):
    """
    Collect basic features, box features and mask features of each detected nucleus

    Args:
    :param processed_pred: (dict) processed prediction results without overlapping
    :param model_classes: (list) classes setting of the HD-Staining model
    :param box_features: (torch.Tensor) box features for each proposal from the rpn of the HD-Staining model
    :param pred_boxes: (numpy.array) predicted boxes for each proposal from the rpn of the HD-Staining model
    :param pred_scores: (numpy.array) predicted scores for each proposal from the rpn of the HD-Staining model
    :param mask_features: (torch.Tensor) mask features for each detected nucleus

    :return:
        a form containing the feature information of each nucleus on the whole patch
    """
    # Extract results of different categories from processed_pred
    masks = processed_pred['masks']
    class_ids = processed_pred['class_ids']
    boxes = processed_pred['boxes']
    scores = processed_pred['scores']
    
    # Define the column_names of the result form
    column_names = ['nucleus_id', 'nucleus_class', 'centroid_x0', 'centroid_y0', 'area', 'convex_area', 'eccentricity',
                    'extent', 'filled_area', 'major_axis_length', 'minor_axis_length', 'orientation', 'perimeter',
                    'solidity', 'bbox_x1', 'bbox_y1', 'bbox_x2', 'bbox_y2', 'probability', 'probability_vector']
    for i in range(0, box_features.size()[1]):
        column_name = 'box_feature_' + str(i+1)
        column_names.append(column_name)
    for i in range(0, mask_features.size()[1]):
        column_name = 'mask_feature_' + str(i+1)
        column_names.append(column_name)
    
    # Collect the feature information of each nucleus in the form
    nucleus_form = []
    for target_index in range(0, len(class_ids)):
        # Get the identity information of the target nucleus
        nucleus_id = str(target_index)
        nucleus_class = model_classes[class_ids[target_index]-1]
        target_basic_features = [nucleus_id, nucleus_class]
        # Get the morphology features of the target nucleus
        target_mask = masks[..., target_index]
        target_properties = skimage.measure.regionprops(target_mask)[0]
        target_basic_features.extend([target_properties.centroid[1], target_properties.centroid[0], 
                                      target_properties.area, target_properties.convex_area,
                                      target_properties.eccentricity, target_properties.extent, 
                                      target_properties.filled_area, target_properties.major_axis_length, 
                                      target_properties.minor_axis_length, target_properties.orientation, 
                                      target_properties.perimeter, target_properties.solidity])
        # Get the bbox information of the target nucleus
        target_basic_features.extend(boxes[target_index].tolist())
        # Get the probability information of the target nucleus
        target_basic_features.append(scores[target_index])
        # Get the box features of the target nucleus
        box_list = [i for i, val in enumerate(pred_boxes) if np.all(val==boxes[target_index])]
        score_list = np.where(pred_scores==scores[target_index])[0].tolist()
        reshaped_index = list(set(box_list).intersection(set(score_list)))[0]
        proposal_index = reshaped_index // (len(model_classes)+1)
        target_basic_features.append(pred_scores[(proposal_index)*(len(model_classes)+1):
                                                 (proposal_index+1)*(len(model_classes)+1)])
        target_box_features = box_features[proposal_index].detach().cpu().numpy().tolist()
        # Get the mask features of the target nucleus
        target_mask_features = mask_features[target_index]
        target_mask_features = torch.nn.AvgPool2d(target_mask_features.size()[-1])(target_mask_features)
        target_mask_features = target_mask_features.detach().cpu().numpy().reshape(-1).tolist()
        # Gather all features of the target nucleus
        target_nucleus_form = target_basic_features + target_box_features + target_mask_features
        nucleus_form.append(target_nucleus_form)
    nucleus_form = pd.DataFrame(data=nucleus_form, columns=column_names)
    return nucleus_form

def select_central_nucleus(nucleus_form, patch_size=(512, 512), patch_rim=0):
    """
    Select the nucleus in the main region of the patch

    Args:
    :param nucleus_form: (dataframe) a form containing the feature information of each nucleus on the whole patch
    :param patch_size: (tuple) a tuple containing two numbers (the first one indicating height and the second one
    indicating width of the patch)
    :param patch_rim: (int) width of the rim around the main region of the patch

    :return:
        a form containing the feature information of each nucleus in the main region of the patch
    """
    central_nucleus_form = nucleus_form.copy()
    for target_index in range(0, len(nucleus_form)):
        centroid_y0 = nucleus_form['centroid_y0'].values[target_index]
        centroid_x0 = nucleus_form['centroid_x0'].values[target_index]
        if patch_rim <= centroid_y0 < (patch_size[0]-patch_rim) and patch_rim <= centroid_x0 < (patch_size[1]-patch_rim):
            central_nucleus_form = central_nucleus_form
        else:
            central_nucleus_form = central_nucleus_form.drop(nucleus_form.index[target_index])
    central_nucleus_form = central_nucleus_form.reset_index(drop=True)
    return central_nucleus_form

def modify_nucleus_form(nucleus_form, patch_name='', mag_ratio=1):
    """
    Modify nucleus id and centroid location information

    Args:
    :param nucleus_form: (dataframe) a form containing the feature information of each nucleus in the main region of 
    the patch
    :param patch_name: (string) name containing location information of the patch to the whole slide (the number in
    front of 'x' indicating height location and number behind 'x' indicating width location)
    :param mag_ratio: (float) ratio between model magnitude and image magnitude

    :return:
        a form containing the feature information of each nucleus in the main region of the patch 
        (location information is the location on the original whole slide)
    """
    # Get location information of the target patch to the whole slide
    if len(patch_name) != 0:
        patch_id = patch_name + '_'
        patch_location_h = int(re.findall('[0-9]+(?=x)', patch_name)[-1])
        patch_location_w = int(re.findall('(?<=x)[0-9]+', patch_name)[-1])
        patch_location = (patch_location_h, patch_location_w)
    else:
        patch_id = patch_name
        patch_location = (0, 0)
    
    # Update information for each nucleus
    modified_nucleus_form = nucleus_form.copy()
    for target_index in range(0, len(nucleus_form)):
        # Update nucleus_id of the target nucleus
        nucleus_id = str(target_index+1)
        new_nucleus_id = patch_id + nucleus_id
        modified_nucleus_form.at[target_index, 'nucleus_id'] = new_nucleus_id
        # Update centroid information of the target nucleus
        centroid_x0 = nucleus_form['centroid_x0'].values[target_index]
        new_centroid_x0 = patch_location[1] + int(centroid_x0/mag_ratio)
        modified_nucleus_form.at[target_index, 'centroid_x0'] = new_centroid_x0
        centroid_y0 = nucleus_form['centroid_y0'].values[target_index]
        new_centroid_y0 = patch_location[0] + int(centroid_y0/mag_ratio)
        modified_nucleus_form.at[target_index, 'centroid_y0'] = new_centroid_y0
    # Change the type of centroid columns
    modified_nucleus_form = modified_nucleus_form.astype({'centroid_x0': int, 'centroid_y0': int})
    return modified_nucleus_form

def get_predicted_mask(processed_pred, model_classes, rgb_markers, bg_color=[255, 255, 255]):
    """
    Generate a colorful mask based on processed prediction results

    Args:
    :param processed_pred: (dict) processed prediction results without overlapping
    :param model_classes: (list) classes setting of the HD-Staining model
    :param rgb_markers: (dict) colors setting of the HD-Staining model (except background)
    :param bg_color: (list) color setting for background

    :return
        a mask containing all classes of nuclei labelled by different colors
    """
    masks = processed_pred['masks']
    class_ids = processed_pred['class_ids']
    predicted_mask = np.zeros((masks.shape[0], masks.shape[1], 3), dtype=np.uint8)
    predicted_mask[:, :] = bg_color  # Background
    for target_index in range(masks.shape[2]):
        predicted_mask[masks[:, :, target_index]==1] = rgb_markers[model_classes[class_ids[target_index]-1]]
    return predicted_mask

def plot_result_images(original_image, model_input, predicted_mask, model_mag=40, image_mag=40, patch_rim=0):
    """
    Plot the result images

    Args:
    :param original_image: (numpy matrix) matrix of the original patch image
    :param model_input: (numpy matrix) preprocessed patch image for model input
    :param predicted_mask: (numpy matrix) a RGB image with different colors indicating different categories of nuclei
    :param model_mag: (int) magnitude of the HD-Staining model
    :param image_mag: (int) magnitude of the original patch image
    :param patch_rim: (int) width of the rim around the main region of the patch
    
    :return
        plot the result images directly on the page
    """
    # Get size information of model_input
    model_input_size = model_input.shape[0:2]
    
    # Plot the images
    fig, axes = plt.subplots(1, 3, figsize=(18, 18))
    ax = axes.ravel()
    ax[0].imshow(original_image)
    ax[0].set_title('Original Image ({}x)'.format(image_mag))
    ax[1].imshow(model_input)
    ax[1].set_title('Model Input ({}x)'.format(model_mag))
    ax[2].imshow(predicted_mask)
    ax[2].set_title('Predicted Mask ({}x)'.format(model_mag))
    
    # Add a rectangle to predicted_mask for reference
    if patch_rim > 0:
        rect = plt.Rectangle((patch_rim, patch_rim), model_input_size[1]-(2*patch_rim), model_input_size[0]-(2*patch_rim),
                             color='black', linestyle='dashed', linewidth=2, fill=None)
        ax[2].add_patch(rect)
    plt.show(block=True)
    plt.close()

def save_result_images(original_image, model_input, predicted_mask, model_mag=40, image_mag=40, patch_rim=0, 
                       patch_name='', save_dir=''):
    """
    Save the result images

    Args:
    :param original_image: (numpy matrix) matrix of the original patch image
    :param model_input: (numpy matrix) preprocessed patch image for model input
    :param predicted_mask: (numpy matrix) a RGB image with different colors indicating different categories of nuclei
    :param model_mag: (int) magnitude of the HD-Staining model
    :param image_mag: (int) magnitude of the original patch image
    :param patch_rim: (int) width of the rim around the main region of the patch
    :param patch_name: (string) name of the patch image
    :param save_dir: (string) the folder to save the result images

    :return
        save the result images to the target location
    """
    # Get size information of model_input
    model_input_size = model_input.shape[0:2]
    
    # Check patch_name
    if len(patch_name) == 0:
        modified_name = patch_name
    else:
        modified_name = '_' + patch_name
        
    # Save original image
    original_image_dir = os.path.join(save_dir, 'original_image')
    if not os.path.exists(original_image_dir):
        os.makedirs(original_image_dir)
    original_image_name = 'original{}'.format(image_mag) + modified_name + '.png'
    original_image_path = os.path.join(original_image_dir, original_image_name)
    skimage.io.imsave(original_image_path, original_image)

    # Save model input
    model_input_dir = os.path.join(save_dir, 'model_input')
    if not os.path.exists(model_input_dir):
        os.makedirs(model_input_dir)
    model_input_name = 'input{}'.format(model_mag) + modified_name + '.png'
    model_input_path = os.path.join(model_input_dir, model_input_name)
    skimage.io.imsave(model_input_path, model_input)
    
    # Save predicted mask
    predicted_mask_dir = os.path.join(save_dir, 'predicted_mask')
    if not os.path.exists(predicted_mask_dir):
        os.makedirs(predicted_mask_dir)
    predicted_mask_name = 'mask{}'.format(model_mag) + modified_name + '.png'
    predicted_mask_path = os.path.join(predicted_mask_dir, predicted_mask_name)
    # Add a rectangle to predicted_mask for reference depending on the value of patch_rim
    if patch_rim > 0:
        plt.figure(figsize=(15, 15))
        plt.imshow(predicted_mask)
        plt.axis('off')
        plt.margins(0, 0)
        rect = plt.Rectangle((patch_rim, patch_rim), model_input_size[1]-(2*patch_rim), model_input_size[0]-(2*patch_rim),
                             color='black', linestyle='dashed', linewidth=2, fill=None)
        plt.gca().add_patch(rect)
        plt.gca().xaxis.set_major_locator(plt.NullLocator())
        plt.gca().yaxis.set_major_locator(plt.NullLocator())
        plt.savefig(predicted_mask_path, bbox_inches='tight', pad_inches=0)
        plt.close()
    else:
        skimage.io.imsave(predicted_mask_path, predicted_mask)

def apply_hd_staining_to_patch(model, model_parameters, dataset_config, patch_image, patch_name='', model_mag=40, 
                               image_mag=40, patch_rim=0, save_form=False, plot_image=False, save_image=False, 
                               save_dir=''):
    """
    Apply the HD-Staining model to a single patch

    Args:
    :param model: the HD-Staining model for nuclei segmentation and classification
    :param model_parameters: (class) parameters required for the HD-Staining model
    :param dataset_config: (dict) dataset config for inference
    :param patch_image: (numpy matrix) matrix of the original patch image
    :param patch_name: (string) name containing location information of the patch to the whole slide (the number in
    front of 'x' indicating height location and number behind 'x' indicating width location)
    :param model_mag: (int) magnitude of the HD-Staining model
    :param image_mag: (int) magnitude of the original patch image
    :param patch_rim: (int) width of the rim around the main region of the patch
    :param save_form: (bool, optional) if True, save the form about nucleus information, default is False
    :param plot_image: (bool, optional) if True, plot the result images, default is False
    :param save_image: (bool, optional) if True, save the result images, default is False
    :param save_dir: (string) the folder to save analysis results

    :return
        a form containing the feature information of each nucleus in the main region of the patch
        result images:
        - original image
        - model input
        - predicted mask
    
    :raise:
        IOError: an error occurs if patch_rim is not in the range of [0, half of patch height/width)
    """
    # Get size information of patch_image
    patch_size = patch_image.shape[0:2]
    
    # Check the value of patch_rim
    if not (0 <= patch_rim < (0.5*patch_size[0]) and 0 <= patch_rim < (0.5*patch_size[1])):
        raise IOError('Please put appropriate number in the argument of patch_rim [0, half of patch height/width)')
    
    # Calculate the ratio between model_mag and image_mag
    mag_ratio = model_mag / image_mag
    model_input_rim = int(patch_rim*mag_ratio)
    
    # Convert the image format from numpy.array to torch.Tensor
    image_tensor = format_image(patch_image, dataset_config['normalizer'], model.netG.device, mag_ratio)
    
    # Run detection
    _, pred = model.netG(image_tensor, is_20x=False)
    
    # Post-process
    processed_pred = postprocess_prediction(pred, ratio_thresh=0.6)
    
    # Check whether there is any nucleus on the target patch
    if len(processed_pred['class_ids']) == 0:
        if len(patch_name) == 0:
            print('Stop analyzing this patch because of no nucleus on this patch')
        else:
            print('Stop analyzing ({}) because of no nucleus on this patch'.format(patch_name))
        return[]
    
    # Get features and proposals from the HD-Staining model
    image_imagelist, _ = model.netG.transform(image_tensor, None)
    model_input_size = image_imagelist.image_sizes[0]
    # Shift resnet 1st conv2d to stride = 2
    model.netG.backbone.body.conv1 = model.netG.conv1_40x
    model.netG.backbone.to(model.netG.device)
    features = model.netG.backbone(image_imagelist.tensors)
    proposals, _ = model.netG.rpn(image_imagelist, features, None)
    
    # Get box features from the HD-Staining model
    box_features, pred_boxes, pred_scores = get_box_features(model, features, proposals, model_input_size)
    
    # Get mask features from the HD-Staining model
    mask_features = get_mask_features(model, processed_pred, features, model_input_size)
    
    # Gather nucleus information in the form
    nucleus_form = get_nucleus_features(processed_pred, model_parameters.classes, box_features, pred_boxes, 
                                        pred_scores, mask_features)
    nucleus_form = select_central_nucleus(nucleus_form, model_input_size, model_input_rim)
    nucleus_form = modify_nucleus_form(nucleus_form, patch_name, mag_ratio)
    
    if save_form:
        if len(patch_name) == 0:
            form_name = 'nucleus_information_model{}_image{}.csv'.format(model_mag, image_mag)
        else:
            form_name = '({})_information_model{}_image{}.csv'.format(patch_name, model_mag, image_mag)
        form_path = os.path.join(save_dir, form_name)
        nucleus_form.to_csv(form_path, index=False)
    
    if plot_image or save_image:
        displayed_model_input = uimg_d.RGB_Normalizer(mean=model_parameters.stain_mean, std=model_parameters.stain_std, 
                                                      inverse=True)(image_tensor[0].permute(1, 2, 0).detach().cpu().numpy())
        predicted_mask = get_predicted_mask(processed_pred, model_parameters.classes, model_parameters.rgb_markers, 
                                            bg_color=[255, 255, 255])
    
    if plot_image:
        plot_result_images(patch_image, displayed_model_input, predicted_mask, model_mag, image_mag, model_input_rim)
    
    if save_image:
        save_result_images(patch_image, displayed_model_input, predicted_mask, model_mag, image_mag, model_input_rim, 
                           patch_name, save_dir)
    return nucleus_form

def get_continuous_patch_parameters(slide, region_parameters, patch_size=(512, 512), patch_rim=0):
    """
    Gather location and size information of each patch by continuous method

    Args:
    :param slide: (array) image object
    :param region_parameters: (tuple) location information (min_row, min_col, max_row, max_col) of the main region of
    the slide
    :param patch_size: (tuple) a tuple containing two numbers (the first one indicating height and the second one
    indicating width of the patch)
    :param patch_rim: (int) width of the rim around the main region of the patch

    :return:
        a list containing location and size information of all patches generated from the main region of the slide
        (location information is the location on the original whole slide)
    """
    # Get parameters of the main region of the slide and also single patch
    region_height = region_parameters[2] - region_parameters[0] - (2*patch_rim)
    region_width = region_parameters[3] - region_parameters[1] - (2*patch_rim)
    patch_height, patch_width = patch_size
    patch_region_height = patch_height - (2*patch_rim)
    patch_region_width = patch_width - (2*patch_rim)

    # Get parameters to extract the target patch from the slide
    patch_parameters = []
    for h in range(0, region_height, patch_region_height):
        if region_height - h < patch_region_height:
            target_height = region_height % patch_region_height + (2*patch_rim)
        else:
            target_height = patch_height
        for w in range(0, region_width, patch_region_width):
            if region_width - w < patch_region_width:
                target_width = region_width % patch_region_width + (2*patch_rim)
            else:
                target_width = patch_width
            # Transfer the location on the modified main region of the slide to the location on the original whole slide
            target_patch_location = (h+region_parameters[0], w+region_parameters[1])
            target_patch_size = (target_height, target_width)
            # Check whether there is enough signal in the target patch
            target_patch = slide[target_patch_location[0]:(target_patch_location[0]+target_patch_size[0]), 
                                 target_patch_location[1]:(target_patch_location[1]+target_patch_size[1]), :]
            if check_white(target_patch):
                continue
            patch_parameters.append((target_patch_location, target_patch_size))
    return patch_parameters

def choose_random_pixel(region_parameters, patch_size=(512, 512)):
    """
    Randomly choose one pixel in the input matrix

    Args:
    :param region_parameters: (tuple) location information (min_row, min_col, max_row, max_col) of the main region of
    the slide
    :param patch_size: (tuple) a tuple containing two numbers (the first one indicating height and the second one
    indicating width of the patch)

    :return
        a tuple containing location information of the selected pixel (location information is the location on the
        modified main region of the slide)
    """
    region_height = region_parameters[2] - region_parameters[0]
    region_width = region_parameters[3] - region_parameters[1]
    selected_h = np.random.randint(0, region_height-patch_size[0])
    selected_w = np.random.randint(0, region_width-patch_size[1])
    selected_location = (selected_h, selected_w)
    return selected_location

def get_random_patch_parameters(slide, region_parameters, patch_size=(512, 512), patch_num=0, plot_mask=False):
    """
    Gather location and size information of each patch by random method

    Args:
    :param slide: (array) image object
    :param region_parameters: (tuple) location information (min_row, min_col, max_row, max_col) of the main region of
    the slide
    :param patch_size: (tuple) a tuple containing two numbers (the first one indicating height and the second one
    indicating width of the patch)
    :param patch_num: (int) the number of patches to be randomly extracted
    :param plot_mask: (bool, optional) if True, plot the extracted mask, default is False

    :return:
        a list containing location and size information of patches randomly selected from the main region of the slide
        (location information is the location on the original whole slide)
    """
    if plot_mask:
        # Draw an empty mask
        mask = np.zeros(slide.shape[0:2], dtype=np.uint8)
        mask[region_parameters[0]:region_parameters[2],
             region_parameters[1]:region_parameters[3]] = 255

    patch_parameters = []
    effective_loop = 0
    while effective_loop < patch_num:
        # Randomly choose a pixel as the top-left point of the patch
        selected_patch_location = choose_random_pixel(region_parameters, patch_size)
        # Transfer the location on the modified main region of the slide to the location on the original whole slide
        selected_patch_location = (selected_patch_location[0]+region_parameters[0], 
                                   selected_patch_location[1]+region_parameters[1])
        # Check whether there is enough signal in the selected patch
        selected_patch = slide[selected_patch_location[0]:(selected_patch_location[0]+patch_size[0]), 
                               selected_patch_location[1]:(selected_patch_location[1]+patch_size[1]), :]
        if check_white(selected_patch):
            continue
        effective_loop += 1
        patch_parameters.append((selected_patch_location, patch_size))
        # Label corresponding region in the mask
        if plot_mask:
            mask[selected_patch_location[0]:(selected_patch_location[0]+patch_size[0]),
                 selected_patch_location[1]:(selected_patch_location[1]+patch_size[1])] = 0
    
    if plot_mask:
        fig, axes = plt.subplots(1, 2, figsize=(12, 12))
        ax = axes.ravel()
        ax[0].imshow(slide)
        ax[0].set_title('Slide')
        ax[1].imshow(mask)
        ax[1].set_title('Mask')
        plt.show(block=True)
        plt.close()
    return patch_parameters

def get_single_patch(slide, patch_parameters, slide_id=''):
    """
    Extract one patch from the original whole slide according to its location and size information

    Args:
    :param slide: (array) image object
    :param patch_parameters: (tuple) location and size information of the target patch (the first element indicating
    patch location and the second element indicating patch size)
    :param slide_id: (string) name of the slide

    :return:
        - patch_image: the image of the target patch
        - patch_name: the name of the target patch in the format of [(slide_id)]_[h_location]x[w_location]
    """
    # Get the image of the target patch
    patch_location = patch_parameters[0]
    patch_size = patch_parameters[1]
    patch_image = slide[patch_location[0]:(patch_location[0]+patch_size[0]), 
                        patch_location[1]:(patch_location[1]+patch_size[1]), :]
    
    # Determine the name of the target patch
    if len(slide_id) != 0:
        patch_name = '_'.join(['('+slide_id+')', 'x'.join([str(patch_location[0]), str(patch_location[1])])])
    else:
        patch_name = 'x'.join([str(patch_location[0]), str(patch_location[1])])
    return patch_image, patch_name

def apply_hd_staining_to_slide(model, model_parameters, dataset_config, slide, slide_id, model_mag=40, 
                               image_mag=40, region_parameters=(0, 0, 0, 0), patch_method='continuous',
                               patch_size=(512, 512), patch_rim=0,  patch_num=0, save_form=False, 
                               save_image=False, save_patch_num=0, save_dir=''):
    """
    Apply the HD-Staining model to a slide

    Args:
    :param model: the HD-Staining model for nuclei segmentation and classification
    :param model_parameters: (class) parameters required for the HD-Staining model
    :param dataset_config: (dict) dataset config for inference
    :param slide: (array) image object
    :param slide_id: (string) name of the slide
    :param model_mag: (int) magnitude of the HD-Staining model
    :param image_mag: (int) magnitude of the original patch image
    :param region_parameters: (tuple) location information (min_row, min_col, max_row, max_col) of the main region of
    the slide
    :param patch_method: method to generate patches ('continuous' or 'random')
    :param patch_size: (tuple) a tuple containing two numbers (the first one indicating height and the second one
    indicating width of the patch)
    :param patch_rim: (int) width of the rim around the main region of the patch
    :param patch_num: (int) if patch_method is 'random', the number of patches to be randomly extracted
    :param save_form: (bool, optional) if True, save the nucleus information form of all analyzed patches,
    default is False
    :param save_image: (bool, optional) if True, save the result images, default is False
    :param save_patch_num: (int) if save_image is True, the number of patches whose result images to be saved
    :param save_dir: (string) the folder to save analysis results

    :return
        a form containing the feature information of each nucleus in the main region of all analyzed patches
        result images:
        - original image
        - model input
        - predicted mask
    
    :raise:
        IOError: an error occurs if the patch_method is not well defined.
        IOError: an error occurs if patch_method is 'random' but patch_num is less than one.
        IOError: an error occurs if save_image is True and save_patch_num is less than one.
    """
    # Create an empty folder to save analysis results for the target slide
    if save_image or save_form:
        save_dir = os.path.join(save_dir, slide_id)
        if not os.path.exists(save_dir):
            os.makedirs(save_dir)
    
    # Get patch_parameters
    if patch_method == 'continuous':
        patch_parameters = get_continuous_patch_parameters(slide, region_parameters, patch_size, patch_rim)
    elif patch_method == 'random':
        if patch_num < 1:
            raise IOError('Please put appropriate number in the argument of patch_num (current number is too small)')
        else:
            patch_parameters = get_random_patch_parameters(slide, region_parameters, patch_size, patch_num, 
                                                           plot_mask=True)
    else:
        raise IOError('Please specify the method to generate patches: continuous or random')
        
    # Randomly select the patches whose results to be saved
    total_patch_num = len(patch_parameters)
    print('Total number of patches to be analyzed: {}'.format(total_patch_num))
    if save_image:
        if save_patch_num < 1:
            raise IOError('Please put appropriate number in the argument of save_patch_num (current number is too small)')
        elif save_patch_num >= total_patch_num:
            print('Save the result images of all patches')
            selected_save_index = np.array(range(0, total_patch_num))
        else:
            print('Save the result images of {} patches'.format(save_patch_num))
            selected_save_index = np.random.choice(range(0, total_patch_num), size=save_patch_num, replace=False)
    
    # Apply analysis to every single patch
    final_form = pd.DataFrame()
    for target_index in range(0, total_patch_num):
        patch_image, patch_name = get_single_patch(slide, patch_parameters[target_index], slide_id)
        modified_patch_image = np.zeros((patch_size[0], patch_size[1], 3), dtype=np.uint8)
        modified_patch_image[:, :, :] = 255
        modified_patch_image[0:patch_image.shape[0], 0:patch_image.shape[1], :] = patch_image
        print('----------------------------------------------------------------------------')
        print('Start to analyze: {}'.format(patch_name))
        if save_image:
            if target_index in selected_save_index:
                print('Save the result images of this patch')
                patch_form = apply_hd_staining_to_patch(model, model_parameters, dataset_config, modified_patch_image, 
                                                        patch_name, model_mag, image_mag, patch_rim, save_form=False, 
                                                        plot_image=False, save_image=True, save_dir=save_dir)
            else:
                patch_form = apply_hd_staining_to_patch(model, model_parameters, dataset_config, modified_patch_image, 
                                                        patch_name, model_mag, image_mag, patch_rim, save_form=False, 
                                                        plot_image=False, save_image=False, save_dir=save_dir)
        else:
            patch_form = apply_hd_staining_to_patch(model, model_parameters, dataset_config, modified_patch_image, 
                                                    patch_name, model_mag, image_mag, patch_rim, save_form=False, 
                                                    plot_image=False, save_image=False, save_dir=save_dir)
        # Store nucleus information of the target patch
        if len(patch_form) != 0:
            if len(final_form) == 0:
                final_form = patch_form
            else:
                final_form = final_form.append(patch_form, ignore_index=True)
    
    if save_form:
        form_name = '({})_information_model{}_image{}.csv'.format(slide_id, model_mag, image_mag)
        form_path = os.path.join(save_dir, form_name)
        final_form.to_csv(form_path, index=False)
    return final_form



def parse_args():
    parser = argparse.ArgumentParser(
        description="Apply HD-Staining model to whole-slide images."
    )
    parser.add_argument(
        "--input-dir",
        type=str,
        default="./example_data",
        help="Input directory containing .tif/.svs WSIs.",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="./output/",
        help="Output directory for results.",
    )
    parser.add_argument(
        "--model-dir",
        type=str,
        default=BREAST_MODEL_ROOT,
        help="Directory containing the pre-trained HD-Staining model.",
    )
    parser.add_argument(
        "--slide-id",
        type=str,
        default="CytAssist_11mm_FFPE_Human_Ovarian_Carcinoma_tissue_image",
        help="Slide ID (without extension) to analyze.",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="cuda:0",
        help="Torch device (e.g., 'cuda:0' or 'cpu').",
    )
    return parser.parse_args()


def main():
    args = parse_args()

    device = torch.device(args.device)

    # ------------------------------------------------------------
    # Prepare model + dataset configuration
    # ------------------------------------------------------------
    model_params = ModelParameters()
    dataset_config_infer = get_inference_dataset_config()

    print(f"Model config: {MODEL_CONFIG}")
    print(f"\nDataset config: {dataset_config_infer}")

    # Load model
    model_test = MaskRCNNModel_NuCLS(
        MODEL_CONFIG,
        model_params.classes,
        is_train=False,
        device=device,
        save_dir=args.model_dir,
        pretrained_mrcnn=False,
    )

    # Fixed epoch checkpoint
    FIXED_EPOCH = 65
    print(f"Loading model weights from epoch {FIXED_EPOCH}...")
    model_test.load_networks(FIXED_EPOCH)
    model_test.netG.eval()

    # ------------------------------------------------------------
    # Slide list (you can pass only one slide via CLI, still works)
    # ------------------------------------------------------------
    slide_list = [args.slide_id]

    target_model_mag = 40

    # Dictionaries to fill dynamically
    image_mag = {}          # magnification per slide
    region_parameters = {}  # (min_row, min_col, max_row, max_col)

    print("------------------------------------------------------")
    print("Building region parameters using OpenSlide...")
    print("------------------------------------------------------")

    for slide_id in slide_list:
        svs_path = os.path.join(args.input_dir, slide_id + ".svs")

        # Read slide dimensions via OpenSlide
        slide_os = openslide.OpenSlide(svs_path)
        width, height = slide_os.dimensions  # returns (width, height)

        region_parameters[slide_id] = (0, 0, height, width)

        # If magnification differs between slides, add logic here
        image_mag[slide_id] = 20

        print(f"{slide_id}: size = (H={height}, W={width})")

    print("Final region parameters:", region_parameters)

    # ------------------------------------------------------------
    # Run inference for each slide
    # ------------------------------------------------------------
    for slide_id in slide_list:

        print("----------------------------------------------------------------------------")
        print("----------------------------------------------------------------------------")
        print(f"Start to analyze: {slide_id}")

        # Load the actual pixel data (TIFF)
        tif_path = os.path.join(args.input_dir, slide_id + ".tif")
        target_slide = np.array(tiff.imread(tif_path))

        target_image_mag = image_mag[slide_id]
        target_region_parameters = region_parameters[slide_id]

        # Compute patch size based on magnification
        target_patch_size = (
            int(512 / (target_model_mag / target_image_mag)),
            int(512 / (target_model_mag / target_image_mag)),
        )
        target_patch_rim = int(30 / (target_model_mag / target_image_mag))

        # Run the full HD-Staining analysis
        _ = apply_hd_staining_to_slide(
            model_test,
            model_params,
            dataset_config_infer,
            target_slide,
            slide_id,
            model_mag=target_model_mag,
            image_mag=target_image_mag,
            region_parameters=target_region_parameters,
            patch_method="continuous",
            patch_size=target_patch_size,
            patch_rim=target_patch_rim,
            patch_num=0,
            save_form=True,
            save_image=True,
            save_patch_num=50,
            save_dir=args.output_dir,
        )

    print("Image feature extraction finished.")

if __name__ == "__main__":
    main()